config/routes.rb
BestinTown::Application.routes.draw do
  get "fight/index"
  get "classements/index"
  get "classement/index"
  get "plats/index"
  get "welcome/index"
  get "fight/index"

  resources :etablissements #do
    resources :classement

  resources :classements do
    resources :boissons
    resources :etablissements
  end
  

  resources :boissons #do

  resources :plats
  resources :classement

  resources :fight

  root 'welcome#index'

  

end

app/models/boisson.rb
class Boisson < ActiveRecord::Base
	has_many :classement

end

app/models/classement.rb
class Classement < ActiveRecord::Base
  belongs_to :etablissement
  belongs_to :plat
  belongs_to :boisson

  has_many :etablissement, :include => true

end

app/models/etablissement.rb
class Etablissement < ActiveRecord::Base
	has_many :classement, :include => true
	belongs_to :classement

end

app/models/plat.rb
class Plat < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/boissons_controller.rb
class BoissonsController < ApplicationController
	def index

		@boisson = Boisson.all
		@classement = Classement.all
	end

	def new
		@boissonall = Boisson.all
		@boisson = Boisson.new
	end

	def create
		@boisson = Boisson.new(boisson_params)
		
		if @boisson.save
			redirect_to @boisson
		else
			render 'new'
		end
	end

	def show
		@boisson = Boisson.find(params[:id])
		#Client.find_by! first_name: 'Lifo'
		#where(name: 'David', occupation: 'Code Artist')
		@top_one_boisson = Classement.select("etablissements.name,etablissements.path,etablissements.adresse,classements.point").joins('INNER JOIN etablissements ON etablissements.id = classements.etablissement_id').where(boisson_id: params[:id]).order("point DESC").limit(3)
		#@top_one_boisson = Etablissement.where(classements.boisson_id: params[:id]).joins('INNER JOIN classements ON etablissements.id = classements.etablissement_id').order("point DESC").limit(3)

		#trier par point + ajouter la limit à 3 pour le top 3un
		# et un join sur etablisement pour recuperer les données de l'éetablissement et c'est ok
	end

	private
		def boisson_params
			params.require(:boisson).permit(:name, :description)
		end
end

app/controllers/classements_controller.rb
class ClassementsController < ApplicationController
  
  def index
  	@classement = Classement.all
  end

  def new
  	@classementall = Classement.all
    @boisson = Plat.find(1)
   # Student.joins(:schools).where(schools: { category: 'public' })

  	@classement = Classement.new
  end

  def create
  	@classement = Classement.new(clasmt_param)
		
      if @classement.save
		    redirect_to @classement
      else
		    render 'new'
      end
  end

  def edit
    # @id_etablissement = Post.find(params[:id])
    if params[:id] == "1"
      @type = "Boisson"
      @etab = [params[:id_etablissement]]
      @id_item = [params[:id_item]]

        classement_up = Classement.where(etablissement_id: @etab,boisson_id: @id_item)
        classement_up[0].point = classement_up[0].point + 1
        if classement_up[0].save
          redirect_to fight_path(2)
        end

    elsif params[:id] == "2"
        @type = "Plat"
        @etab = [params[:id_etablissement]]
        @id_item = [params[:id_item]]

        classement_up = Classement.where(etablissement_id: @etab,plat_id: @id_item)
        classement_up[0].point = classement_up[0].point + 1
        if classement_up[0].save
          redirect_to fight_path(1)
        end
    end
  end

  private
  	def clasmt_param
  		params.require(:classement).permit(:boisson_id)
  	end
end

app/controllers/etablissements_controller.rb
class EtablissementsController < ApplicationController
# pouvoir ajouter un etablissement en especifiant ses spécialité
# insert en bdd d'un etabliseemnt
# recup de tous les item pour cheboxes
# ajout pour chaque iteme d'une ligne en bdd ds la table : classement

	def index
	end

	def new
		@etablissement = Etablissement.new
		@classement = Classement.new
		@boisson = Boisson.all
#		@etablissement = Etablissement.select('etablissements.name','etablissements.description')joins('LEFT OUTER JOIN classements ON classements.etablissement_id = etablissements').new
	end

	def create
		@test = :boisson
    	#@etablissement = Etablissement.find(params[:id])
    	#@comment = @etablissement.comments.create(params[:classement].permit(:etablissement_id, :boisson_id))
  		
		#@boisson = Boisson.new(boisson_params)
		
		#if @boisson.save
		#	redirect_to @boisson
		#else
		#	render 'new'
		#end
	end
end

app/controllers/fight_controller.rb
class FightController < ApplicationController
  def index
  	#commencer la fight
  end

  def show 
    @current = params[:id]
  	if params[:id] == "1"
  		@type = "boisson"
  		#User.limit(5).order("RAND()")

  		@item = Boisson.order("RANDOM()").limit(1)
  		@etablissement = Classement.select('etablissements.name,etablissements.id,etablissements.adresse,etablissements.description,etablissements.path').joins('INNER JOIN etablissements ON etablissements.id = classements.etablissement_id').where(boisson_id: @item[0].id).order("RANDOM()").limit(2)
  		#@iten = @item.attributes['']
  	elsif params[:id] == "2"
  		@type = "food"
      @item = Plat.order("RANDOM()").limit(1)
      @etablissement = Classement.select('etablissements.name,etablissements.id,etablissements.adresse,etablissements.description,etablissements.path').joins('INNER JOIN etablissements ON etablissements.id = classements.etablissement_id').where(plat_id: @item[0].id).order("RANDOM()").limit(2)
    
  	end
  	#2 type : show plat ou show boisson
  	#@boisson = Boisson.find(params[:id])
  end

  def update
  	#if @post.update(params[:post].permit(:title, :text))
  	return params[:post]
  end
end

app/controllers/plats_controller.rb
class PlatsController < ApplicationController
	def index
		@plat = Plat.all
    @classement = Classement.all
  end

  def show
		@plat = Plat.find(params[:id])
    @top_one_plat = Classement.select("etablissements.name,etablissements.path,etablissements.adresse,classements.point").joins('INNER JOIN etablissements ON etablissements.id = classements.etablissement_id').where(boisson_id: params[:id]).order("point DESC").limit(3)
  end

  def new
  	@platall = Plat.all
  	@plat = Plat.new
  end

  	def create
  		@plat = Plat.new(plat_params)

  		if @plat.save
  			redirect_to @plat
  		else
  			render 'new'
  		end
  	end

	private
		def plat_params
			params.require(:plat).permit(:name, :description)
		end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boissons_helper.rb
module BoissonsHelper
end

app/helpers/classements_helper.rb
module ClassementsHelper
end

app/helpers/etablissements_helper.rb
module EtablissementsHelper
end

app/helpers/fight_helper.rb
module FightHelper
end

app/helpers/plats_helper.rb
module PlatsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/boissons/index.html.erb
  <div id='main-content'>
    <div id='firstline'>
      <div class='block-boisson' id='first_boisson'>
        <div id='image-boisson'>
          <img alt="Mojito" src="/assets/boisson/<%= @boisson[0].path %>" />
        </div>
        <div id='bottom-block'>
          <div id='icon-bottom'>
            <img alt="Icon-mojito" src="/assets/boire/icon-mojito.png" />
          </div>
          <div id='text-bottom'>
            <%= link_to 'Mojito',boisson_path(1) %>
          </div>
        </div>
      </div>
      <div class='block-boisson' id='firstline-blocktwo'>
        <div id='image-boisson'>
          <img alt="Mojito-concombre" src="/assets/boisson/<%= @boisson[1].path %>" />
          <!-- /= image_tag("boire/hover-cocktails.png") -->
        </div>
        <div id='bottom-block'>
          <div id='icon-bottom'>
            <img alt="Icon-mojito" src="/assets/boire/icon-mojito.png" />
          </div>
          <div id='text-bottom'>
            <%= link_to 'Long Island',boisson_path(2) %>

          </div>
        </div>
      </div>
      <div class='block-boisson' id='firstline-blockthree'>
        <div id='image-boisson'>
          <img alt="Pina" src="/assets/boisson/<%= @boisson[2].path %>" />
        </div>
        <div id='bottom-block'>
          <div id='icon-bottom'>
            <img alt="Icon-mojito" src="/assets/boire/icon-mojito.png" />
          </div>
          <div id='text-bottom'>
            <%= link_to 'Piña colada',boisson_path(3) %>

            
          </div>
        </div>
      </div>
      <div class='block-boisson' id='firstline-finalblock'>
        <div id='image-boisson'>
          <img alt="Margarita" src="/assets/boisson/<%= @boisson[3].path %>" />
        </div>
        <div id='bottom-block'>
          <div id='icon-bottom'>
            <img alt="Icon-margarita" src="/assets/boire/icon-margarita.png" />
          </div>
          <div id='text-bottom'>
            <%= link_to 'Chocolat Chaud',boisson_path(4) %>
          </div>
        </div>
      </div>
    </div>

    <div id='big_two_small'>
  <a href="<%= boisson_path(6) %>">
    <div id='block' class='big'>
      <div id='image-boisson' class='big_im'>
        <img alt="Sunset" src="/assets/boisson/<%= @boisson[5].path %>" />
      </div>  
      <div id='bottom-block' class="big_bottom">
        <div id='icon-bottom' class="topicon">
          <img alt="Icon-etoile" src="/assets/boire/icon-etoile.png" />
        </div>
        <div id='text-bottom'>
           <%= link_to 'Sangria Sunset',boisson_path(6) %>
        </div>
      </div>
    </div>
  </a>
  
  <a href="<%= boisson_path(12) %>">
    <div id='block' class='small'>
      <div id='image-boisson' class="small_im">
        <img alt="Sunset" src="/assets/boisson/<%= @boisson[11].path %>" />
      </div>  
      <div id='bottom-block' class="small_bottom">
         <%= link_to 'Bloody Mary',boisson_path(12) %>
      </div>
    </div>
  </a>

  <a href="<%= boisson_path(13) %>">
    <div id='block' class='small'>
      <div id='image-boisson' class='small_im'>
        <img alt="Sunset" src="/assets/boisson/<%= @boisson[12].path %>" />
      </div> 
      <div id='bottom-block' class="small_bottom">
        <%= link_to 'Daiquiri',boisson_path(13) %>
      </div> 
    </div>
  </a>

</div>
 <div id='firstline'>
      <div class='block-boisson' id='first_boisson'>
        <div id='image-boisson'>
          <img alt="Mojito" src="/assets/boisson/<%= @boisson[4].path %>" />
        </div>
        <div id='bottom-block'>
          <div id='icon-bottom'>
            <img alt="Icon-mojito" src="/assets/boire/icon-margarita.png" />
          </div>
          <div id='text-bottom'>
            <%= link_to 'Margarita',boisson_path(5) %>
          </div>
        </div>
      </div>
      <div class='block-boisson' id='firstline-blocktwo'>
        <div id='image-boisson'>
          <img alt="Mojito-concombre" src="/assets/boisson/<%= @boisson[6].path %>" />
          <!-- /= image_tag("boire/hover-cocktails.png") -->
        </div>
        <div id='bottom-block'>
          <div id='icon-bottom'>
            <img alt="Icon-mojito" src="/assets/boire/icon-mojito.png" />
          </div>
          <div id='text-bottom'>
            <%= link_to 'Limonade',boisson_path(7) %>

          </div>
        </div>
      </div>
      <div class='block-boisson' id='firstline-blockthree'>
        <div id='image-boisson'>
          <img alt="Pina" src="/assets/boisson/<%= @boisson[7].path %>" />
        </div>
        <div id='bottom-block'>
          <div id='icon-bottom'>
            <img alt="Icon-mojito" src="/assets/boire/icon-mojito.png" />
          </div>
          <div id='text-bottom'>
            <%= link_to 'Biere',boisson_path(8) %>

            
          </div>
        </div>
      </div>
      <div class='block-boisson' id='firstline-finalblock'>
        <div id='image-boisson'>
          <img alt="Margarita" src="/assets/boisson/<%= @boisson[10].path %>" />
        </div>
        <div id='bottom-block'>
          <div id='icon-bottom'>
            <img alt="Icon-margarita" src="/assets/boire/icon-margarita.png" />
          </div>
          <div id='text-bottom'>
            <%= link_to 'Cosmopolitan',boisson_path(11) %>
          </div>
        </div>
      </div>
    </div>

  </div>

app/views/boissons/new.html.erb
<h1>New Boissons</h1>
<%# <%= link_to 'New Boisson', new_boissons_path %>
<% @boissonall.each do |a| %>
	<%= a.name %>
<% end %>

<%= form_for @boisson do |f| %>
  <% if @boisson.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@boisson.errors.count, "error") %> prohibited
      this post from being saved:</h2>
    <ul>
    <% @boisson.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', boissons_path %>

app/views/boissons/show.html.erb
<%= stylesheet_link_tag    "boissons", media: "all", "data-turbolinks-track" => true %>

  <div id='main-content'>
  	<h1>Où boire des <%= @boisson.name %>s ?</h1>
    <div id='big_two_small'>
		<% @top_one_boisson.each.with_index do |z,index| %>
			<% if index == 0 %>
				<div id='topone'>
        	<div id='image-boisson'>
              <div id='icon-bottom'>
              <!--<img alt="Icon-etoile" src="/assets/boire/icon-etoile.png" />-->
              #1
            </div>
        		<img alt="Sunset" src="/assets/bar/<%= z.path %>" />

          </div>
        	<div id='bottom-block'>
         		<div id="title-etab">
                <%= z.name %>
            </div>
         		<div id="location">
                 <img alt="locatationpoint" src="/assets/pointer.png" >
                  <span><%= z.adresse %></span>
            </div>

            <div id="vote">
                <p><span><%= z.point %></span> votes</p>
            </div>
             
        			
          </div>
        </div>
      <% else %>
      <div id="toptwo">

        <div id='image-boisson'>
            <% @css = "" %>
            <% if index == 2 %>
             <% @css = "greentop" %>
            <% end %> 
              <div id='icon-bottom' class="<%= @css %>">
              <!--<img alt="Icon-etoile" src="/assets/boire/icon-etoile.png" />-->
              #<%= index + 1 %>
            </div>
            
    			<img alt="<%= z.path %>" src="/assets/bar/<%= z.path %>" />
        </div>
     			<div id='bottom-block'>
            <img alt="locatationpoint" src="/assets/pointer.png" >
           	<div id='text-bottom'>
             	                 
              <%= z.name %>
            
      	 			<span> votes </span><span class="green"> <%= z.point %></span>
     				</div>
    			</div>
      	</div>
    
          	<% end %>

				
			
		<% end %>
      <!--
      <div id='toptwo'>

       <div id='toptwo'>
        <div id='image-boisson'>
          <img alt="Sunset" src="/assets/boire/sunset.png" />
          <div id='bottom-block'>
            <div id='icon-bottom'>
              <img alt="Icon-etoile" src="/assets/boire/icon-etoile.png" />
            </div>
            <div id='text-bottom'>
              La sangria sunset
            </div>
          </div>
        </div>
      </div>
    </div>-->
    
  </div>
</div>

app/views/classements/edit.html.erb
<h1>Classement#index</h1>
<p>Find me in app/views/classement/index.html.erb</p>

app/views/classements/index.html.erb
<h1>Classement#index</h1>
<p>Find me in app/views/classement/index.html.erb</p>
<%= @classement %>

app/views/classements/new.html.erb
<h1>New Classement</h1>
<%= debug @boisson %>
<%# <%= link_to 'New Boisson', new_boissons_path %>
<% @classementall.each do |a| %>
	<%= a.boisson_id %>
<% end %>
<%= @boisson.name %>



<%= form_for @classement do |f| %>
  <% if @classement.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@classement.errors.count, "error") %> prohibited
      this post from being saved:</h2>
    <ul>
    <% @classement.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :boisson_id %><br>
    <%= f.text_field :boisson_id %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/classements/show.html.erb
<h1>Classement#index</h1>
<p>Find me in app/views/classement/index.html.erb</p>
<%= @classement %>

app/views/etablissements/index.html.erb
<link href='http://fonts.googleapis.com/css?family=Snippet' rel='stylesheet' type='text/css'>

<div id='secondline'>
  <a href="">
    <div id='secondline-bigblock'>
      <div id='image-boisson'>
        <img alt="Sunset" src="/assets/boire/sunset.png" />
        <div id='bottom-block'>
          <div id='icon-bottom'>
            <img alt="Icon-etoile" src="/assets/boire/icon-etoile.png" />
          </div>
          <div id='text-bottom'>
            La sangria sunset
          </div>
        </div>
      </div>
    </div>
    
    <div id='secondline-fourblock'>
      <div id='image-boisson'>
        <img alt="" src="/assets/bar/" />
        <div id='bottom-block'>
          <div id='icon-bottom'>
            <img alt="Icon-etoile" src="/assets/boire/icon-etoile.png" />
          </div>
          <div id='text-bottom'>
          </div>
        </div>
      </div>
    </div>
<!--
    <div id='image-boisson'>
      <img alt="" src="/assets/bar/" />
      <div id='bottom-block'>
        <div id='icon-bottom'>
          <img alt="Icon-etoile" src="/assets/boire/icon-etoile.png" />
        </div>
        <div id='text-bottom'>

      </div>
    </div>
  </div>
      </div>
     
    </div>
   
  </div>-->
</div>

app/views/etablissements/new.html.erb
<h1>Nouvel établissement</h1>
<%= form_for(@etablissement) do |f| %>
  <% if @etablissement.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@etablissement.errors.count, "error") %> prohibited
      this post from being saved:</h2>
    <ul>
    <% @etablissement.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :adresse %><br>
    <%= f.text_area :adresse %>
  </p>
  <p>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>
<%= form_for(@classement) do |f| %>
  <% if @classement.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@classement.errors.count, "error") %> prohibited
      this post from being saved:</h2>
    <ul>
    <% @classement.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <% @boisson.each do |b| %> 
    <p>
      <%= f.label b.name %><br>
      <%= f.check_box :boisson %>
    </p>
   <% end %>
  <p>
    <%= f.label :plat %><br>
    <%= f.text_area :plat %>
  </p>
  <p>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>


<%= link_to 'Back', etablissements_path %>

app/views/fight/index.html.erb
<link href='http://fonts.googleapis.com/css?family=Snippet' rel='stylesheet' type='text/css'>
  <% content_for :boisson do %>
     <%= stylesheet_link_tag  "fight", media: "all", "data-turbolinks-track" => true %>

  <% end %>

<div id="content">	

	<div id='button' class="start_fight">
	<%= link_to 'Start fighting',fight_path(1) %>
	</div>
</div>

app/views/fight/update.html.erb
a

app/views/plats/index.html.erb
   <% content_for :boisson do %>
     <%= stylesheet_link_tag  "plats", media: "all", "data-turbolinks-track" => true %>

  <% end %>

  <div id='main-content'>
    <div id='firstline'>
      <div class='block-boisson' id='first_boisson'>
        <div id='image-boisson'>
          <img alt="Mojito" src="/assets/plat/<%= @plat[0].path %>" />
        </div>
        <div id='bottom-block'>
          <div id='icon-bottom'>
            <img alt="Icon-mojito" src="/assets/boire/sale.png" />
          </div>
          <div id='text-bottom'>
            <%= link_to @plat[0].name,plat_path(1) %>
          </div>
        </div>
      </div>
      <div class='block-boisson' id='firstline-blocktwo'>
        <div id='image-boisson'>
          <img alt="Mojito-concombre" src="/assets/plat/<%= @plat[4].path %>" />
          <!-- /= image_tag("boire/hover-cocktails.png") -->
        </div>
        <div id='bottom-block'>
          <div id='icon-bottom'>
            <img alt="Icon-mojito" src="/assets/boire/sucre.png" />
          </div>
          <div id='text-bottom'>
            <%= link_to @plat[4].name,plat_path(5) %>
          </div>
        </div>
      </div>
      <div class='block-boisson' id='firstline-blockthree'>
        <div id='image-boisson'>
          <img alt="Pina" src="/assets/plat/<%= @plat[2].path %>" />
        </div>
        <div id='bottom-block'>
          <div id='icon-bottom'>
            <img alt="Icon-mojito" src="/assets/boire/sucre.png" />
          </div>
          <div id='text-bottom'>
            <%= link_to @plat[2].name,plat_path(3) %>
          </div>
        </div>
      </div>
      <div class='block-boisson' id='firstline-finalblock'>
        <div id='image-boisson'>
          <img alt="Margarita" src="/assets/plat/<%= @plat[3].path %>" />
        </div>
        <div id='bottom-block'>
          <div id='icon-bottom'>
            <img alt="Icon-margarita" src="/assets/boire/sale.png" />
          </div>
          <div id='text-bottom'>
            <%= link_to @plat[3].name,plat_path(4) %>

          </div>
        </div>
      </div>
    </div>
    <div id='big_two_small'>
  <a href="<%= boisson_path(7) %>">
    <div id='block' class='big'>
      <div id='image-boisson' class='big_im'>
        <img alt="Sunset" src="/assets/plat/<%= @plat[6].path %>" />
      </div>  
      <div id='bottom-block' class="big_bottom">
        <div id='icon-bottom' class="topicon">
          <img alt="Icon-etoile" src="/assets/boire/icon-etoile.png" />
        </div>
        <div id='text-bottom'>
           <%= link_to @plat[6].name,plat_path(7) %>
        </div>
      </div>
    </div>
  </a>
  
  <a href="<%= plat_path(2) %>">
    <div id='block' class='small'>
      <div id='image-boisson' class="small_im">
        <img alt="Sunset" src="/assets/plat/cupc.png" />
      </div>  
      <div id='bottom-block' class="small_bottom">
         <%= link_to @plat[1].name,plat_path(2) %>
      </div>
    </div>
  </a>

  <a href="<%= plat_path(6) %>">
    <div id='block' class='small'>
      <div id='image-boisson' class='small_im'>
        <img alt="Sunset" src="/assets/plat/glace.png" />
      </div> 
      <div id='bottom-block' class="small_bottom">
       <%= link_to @plat[5].name,plat_path(6) %>
      </div> 
    </div>
  </a>

</div>


<% @classement %>

app/views/plats/new.html.erb
<h1>New Plat</h1>
<%# <%= link_to 'New Boisson', new_boissons_path %>
<% @platall.each do |a| %>
	<%= a.name %>
<% end %>

<%= form_for @plat do |f| %>
  <% if @plat.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@plat.errors.count, "error") %> prohibited
      this post from being saved:</h2>
    <ul>
    <% @plat.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/welcome/index.html.erb
  <% content_for :boisson do %>
     <%= stylesheet_link_tag  "welcome", media: "all", "data-turbolinks-track" => true %>

  <% end %>


<div id='big_two_small'>
  <a href="<%= boisson_path(6) %>">
    <div id='block' class='big'>
      <div id='image-boisson' class='big_im'>
        <img alt="Sunset" src="/assets/boire/sunset.png" />
      </div>  
      <div id='bottom-block' class="big_bottom">
        <div id='icon-bottom' class="topicon">
          <img alt="Icon-etoile" src="/assets/boire/icon-etoile.png" />
        </div>
        <div id='text-bottom'>
          La sangria sunset
        </div>
      </div>
    </div>
  </a>
  
  <a href="<%= plat_path(2) %>">
    <div id='block' class='small'>
      <div id='image-boisson' class="small_im">
        <img alt="Sunset" src="/assets/plat/cupc.png" />
      </div>  
      <div id='bottom-block' class="small_bottom">
        La folie des Cupcakes
      </div>
    </div>
  </a>

  <a href="<%= plat_path(6) %>">
    <div id='block' class='small'>
      <div id='image-boisson' class='small_im'>
        <img alt="Sunset" src="/assets/plat/glace.png" />
      </div> 
      <div id='bottom-block' class="small_bottom">
        L'été est (enfin) arrivé : glaces à gogo
      </div> 
    </div>
  </a>
    <!--
          <div id='image-boisson'>
        <img alt="" src="/assets/bar/" />
        <div id='bottom-block'>
          <div id='icon-bottom'>
            <img alt="Icon-etoile" src="/assets/boire/icon-etoile.png" />
          </div>
          <div id='text-bottom'>
          </div>
        </div>
      </div>
    </div>-->
<!--
    <div id='image-boisson'>
      <img alt="" src="/assets/bar/" />
      <div id='bottom-block'>
        <div id='icon-bottom'>
          <img alt="Icon-etoile" src="/assets/boire/icon-etoile.png" />
        </div>
        <div id='text-bottom'>

      </div>
    </div>
  </div>
      </div>
     
    </div>
   
  </div>-->
</div>